In [1]:
!pip list

Package             Version
------------------- -----------
-ip                 20.2.3
argon2-cffi         20.1.0
async-generator     1.10
attrs               20.3.0
backcall            0.2.0
bleach              3.2.1
cffi                1.14.4
colorama            0.4.4
decorator           4.4.2
defusedxml          0.6.0
entrypoints         0.3
ipykernel           5.4.3
ipython             7.19.0
ipython-genutils    0.2.0
ipywidgets          7.6.3
jedi                0.17.2
Jinja2              2.11.2
jsonschema          3.2.0
jupyter             1.0.0
jupyter-client      6.1.11
jupyter-console     6.2.0
jupyter-core        4.7.0
jupyterlab-pygments 0.1.2
jupyterlab-widgets  1.0.0
MarkupSafe          1.1.1
mistune             0.8.4
nbclient            0.5.1
nbconvert           6.0.7
nbformat            5.1.2
nest-asyncio        1.4.3
notebook            6.2.0
numpy               1.19.5
packaging           20.8
pandocfilters       1.4.3
parso               0.7.1
pickleshare         0.7.5

# Tensores
Tensor é um termo utlizado em rede neural responsável por generalizar qualquer vetor idependentemente da sua dimensão.

## Tipos de tensores
https://pytorch.org/docs/stable/tensors.html

In [10]:
import torch

lista = [[1,2,3],
         [4,5,6]]

# Padrão Float32
tns = torch.Tensor(lista)
print(tns.dtype)
print(tns, '\n')

# Padrão Float32
tns = torch.FloatTensor(lista)
print(tns.dtype)
print(tns, '\n')

# Tensor para maior precisão
tns = torch.DoubleTensor(lista)
print(tns.dtype)
print(tns, '\n')

# Tensor de inteiros
tns = torch.LongTensor(lista)
print(tns.dtype)
print(tns, '\n')

# Tensor cuda
tns = torch.cuda.FloatTensor(lista)
print(tns.dtype)
print(tns, '\n')


torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]]) 

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]]) 

torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64) 

torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]]) 

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0') 



## Conversão array numpy para tensores do pytorch

In [16]:
import numpy as np

arr = np.random.rand(3,4)
tns = torch.from_numpy(arr)
print(tns.dtype)
print(tns)

# Torch preserva o tipo dos dados
arr = arr.astype(int)
tns = torch.from_numpy(arr)
print(tns.dtype)
print(tns)

torch.float64
tensor([[0.4506, 0.3994, 0.7787, 0.9867],
        [0.5200, 0.0128, 0.3464, 0.0970],
        [0.8330, 0.6075, 0.2118, 0.6758]], dtype=torch.float64)
torch.int32
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)


## Tensores inicializados

In [27]:
tns1 = torch.ones(2, 3)
tns2 = torch.zeros(4, 5)
tns3 = torch.randn(3, 3)

print(tns1)
print(tns2)
print(tns3)


tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[ 0.2867, -0.1439,  0.7945],
        [ 0.0738,  0.7440,  1.2407],
        [-0.0859, -0.8902,  0.6308]])


## Tensor -> array numpy

In [28]:
arr = tns3.data.numpy()

print(arr)

[[ 0.2867263  -0.1439285   0.7945427 ]
 [ 0.07381617  0.7439583   1.2406746 ]
 [-0.08593495 -0.89021087  0.63082963]]


##  Indexação

In [31]:
print(tns3, '\n')

tns3[0,2] = -10
print(tns3, '\n')

print(tns3[:2])

tensor([[  0.2867,  -0.1439, -10.0000],
        [  0.0738,   0.7440,   1.2407],
        [ -0.0859,  -0.8902,   0.6308]]) 

tensor([[  0.2867,  -0.1439, -10.0000],
        [  0.0738,   0.7440,   1.2407],
        [ -0.0859,  -0.8902,   0.6308]]) 

tensor([[  0.2867,  -0.1439, -10.0000],
        [  0.0738,   0.7440,   1.2407]])


## Operaçoes com tensores

As operações com tensores são realizadas de ponto a ponto, ou seja, o elemento (i ,j) do tensor1 sera operado com o elemnto (i, j) do tensor 2

In [42]:
tns = tns3[:2, :]
print(tns)
print(tns1)

print(tns + tns1)
print(tns * tns1)
print(tns / tns1)

# Multiplicação de matrizer
print(torch.mm(tns, tns1.T))

tensor([[  0.2867,  -0.1439, -10.0000],
        [  0.0738,   0.7440,   1.2407]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 1.2867,  0.8561, -9.0000],
        [ 1.0738,  1.7440,  2.2407]])
tensor([[  0.2867,  -0.1439, -10.0000],
        [  0.0738,   0.7440,   1.2407]])
tensor([[  0.2867,  -0.1439, -10.0000],
        [  0.0738,   0.7440,   1.2407]])
tensor([[-9.8572, -9.8572],
        [ 2.0584,  2.0584]])


## Funçao .size() e .view()
Utilizadas para visualizar a dimensão dos tensores

In [56]:
tns = torch.randn(2,2,3)
print(tns)
print('')

print(tns.size())
print('')
print(tns.view(-1))
print('')
print(tns.view(4, 3))
print('')
print(tns.view(tns.size(), -1))


tensor([[[-0.2861,  0.5498,  0.4420],
         [-0.4252,  0.8089,  1.2333]],

        [[ 0.3693, -1.4883,  0.7112],
         [ 0.0256, -1.1176,  1.1180]]])

torch.Size([2, 2, 3])

tensor([-0.2861,  0.5498,  0.4420, -0.4252,  0.8089,  1.2333,  0.3693, -1.4883,
         0.7112,  0.0256, -1.1176,  1.1180])

tensor([[-0.2861,  0.5498,  0.4420],
        [-0.4252,  0.8089,  1.2333],
        [ 0.3693, -1.4883,  0.7112],
        [ 0.0256, -1.1176,  1.1180]])

tensor([[[-0.2861,  0.5498,  0.4420],
         [-0.4252,  0.8089,  1.2333]],

        [[ 0.3693, -1.4883,  0.7112],
         [ 0.0256, -1.1176,  1.1180]]])


# GPU Cast
É importante definir o dispositivo no inicio do código de acordo com a verificação apresentada a seguir. Esse definição será utilizada toda vez que precisarmos subir valores na GPU, como pesos de rede, gradientes, etc.

In [59]:
if torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device =torch.device('cpu')
print(device)

tns = tns.to(device)
print(tns)

cuda
tensor([[[-0.2861,  0.5498,  0.4420],
         [-0.4252,  0.8089,  1.2333]],

        [[ 0.3693, -1.4883,  0.7112],
         [ 0.0256, -1.1176,  1.1180]]], device='cuda:0')
